name: CI Pipeline - Serenity

on:
  push:
    branches:
      - AutoE2ESerenity
  pull_request:
    branches:
      - AutoE2ESerenity

jobs:
  build-and-test-serenity:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Java
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Configurar cach√© de dependencias Maven
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/AutoE2E-Opcion2/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-


    # 4. Instalar dependencias
    - name: Install dependencies
      working-directory: ./AutoE2E-Opcion2
      run: mvn clean install -DskipTests

    # 5. Ejecutar los tests
    - name: Run Serenity tests
      working-directory: ./AutoE2E-Opcion2
      run: mvn clean verify -Denvironment=chrome "-Dcucumber.filter.tags=@test"

    # 6. Subir reportes de Serenity como artifacts
    - name: Upload Serenity Reports
      if: always()  
      uses: actions/upload-artifact@v3
      with:
        name: serenity-reports
        path: AutoE2E-Opcion2/target/site/serenity/
        retention-days: 5  